namespace MikroPicDesigns.FSMCompiler.v1.Generator.CPP {

    using System;
    using System.IO;
    using System.Text;
    using MicroCompiler.CodeGenerator.Cpp;
    using MicroCompiler.CodeModel;
    using MikroPicDesigns.FSMCompiler.v1.Model;

    public sealed class CPPGenerator : GeneratorBase {

        private readonly CPPGeneratorOptions options;

        public CPPGenerator(GeneratorParameters generatorParameters) {

            CPPGeneratorOptions options = new CPPGeneratorOptions();
            generatorParameters.Populate(options);
            this.options = options;
        }

        public CPPGenerator(CPPGeneratorOptions options) {

            if (options == null) {
                options = new CPPGeneratorOptions();
            }

            this.options = options;
        }

        public override void Generate(Machine machine) {

            if (String.IsNullOrEmpty(options.OutputType) || (options.OutputType == "ContextHeader")) {
                UnitDeclaration contextUnit = ContextUnitGenerator.Generate(machine, options, ContextUnitGenerator.Variant.Header);
                GenerateContextHeader(contextUnit);
            }

            if (String.IsNullOrEmpty(options.OutputType) || (options.OutputType == "ContextCode")) {
                UnitDeclaration contextUnit = ContextUnitGenerator.Generate(machine, options, ContextUnitGenerator.Variant.Code);
                GenerateContextCode(contextUnit);
            }

            if (String.IsNullOrEmpty(options.OutputType) || (options.OutputType == "StateHeader")) {
                UnitDeclaration stateUnit = StateUnitGenerator.Generate(machine, options, StateUnitGenerator.Variant.Header);
                GenerateStateHeader(stateUnit);
            }

            if (String.IsNullOrEmpty(options.OutputType) || (options.OutputType == "StateCode")) {
                UnitDeclaration stateUnit = StateUnitGenerator.Generate(machine, options, StateUnitGenerator.Variant.Code);
                GenerateStateCode(stateUnit);
            }
        }

        private void GenerateContextHeader(UnitDeclaration unitDeclaration) {

            if (!String.IsNullOrEmpty(options.ContextHeaderFileName)) {
                using (StreamWriter writer = File.CreateText(options.ContextHeaderFileName)) {

                    string header = HeaderGenerator.Generate(unitDeclaration);

                    string guardString = Path.GetFileName(options.ContextHeaderFileName).ToUpper().Replace(".", "_");

                    StringBuilder sb = new StringBuilder();
                    sb
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine("// Generated by FsmCompiler v1.1")
                        .AppendLine("// Finite state machine compiler tool")
                        .AppendLine("// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)")
                        .AppendLine("//")
                        .AppendLine("// Warning. Don't touch. Changes will be overwritten!")
                        .AppendLine("//")
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine()
                        .AppendFormat("#ifndef __{0}", guardString).AppendLine()
                        .AppendFormat("#define __{0}", guardString).AppendLine()
                        .AppendLine()
                        .AppendLine()
                        .AppendFormat("#include \"{0}\"", options.ConfigHeaderFileName).AppendLine()
                        .AppendLine()
                        .AppendLine()
                        .AppendLine(header)
                        .AppendLine()
                        .AppendFormat("#endif // __{0}", guardString).AppendLine();

                    writer.Write(sb.ToString());
                }
            }
        }

        private void GenerateContextCode(UnitDeclaration unitDeclaration) {

            if (!String.IsNullOrEmpty(options.ContextCodeFileName)) {
                using (StreamWriter writer = File.CreateText(options.ContextCodeFileName)) {

                    string code = CodeGenerator.Generate(unitDeclaration);

                    StringBuilder sb = new StringBuilder();
                    sb
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine("// Generated by FsmCompiler v1.1")
                        .AppendLine("// Finite state machine compiler tool")
                        .AppendLine("// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)")
                        .AppendLine("//")
                        .AppendLine("// Warning. Don't touch. Changes will be overwritten!")
                        .AppendLine("//")
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine()
                        .AppendLine()
                        .AppendFormat("#include \"{0}\"", options.StateHeaderFileName).AppendLine()
                        .AppendFormat("#include \"{0}\"", options.ContextHeaderFileName).AppendLine()
                        .AppendLine()
                        .AppendLine()
                        .Append(code);

                    writer.Write(sb.ToString());
                }
            }
        }

        private void GenerateStateHeader(UnitDeclaration unitDeclaration) {

            if (!String.IsNullOrEmpty(options.StateHeaderFileName)) {
                using (StreamWriter writer = File.CreateText(options.StateHeaderFileName)) {

                    string header = HeaderGenerator.Generate(unitDeclaration);

                    string guardString = Path.GetFileName(options.StateHeaderFileName).ToUpper().Replace(".", "_");

                    StringBuilder sb = new StringBuilder();
                    sb
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine("// Generated by FsmCompiler v1.1")
                        .AppendLine("// Finite state machine compiler tool")
                        .AppendLine("// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)")
                        .AppendLine("//")
                        .AppendLine("// Warning. Don't touch. Changes will be overwritten!")
                        .AppendLine("//")
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine()
                        .AppendFormat("#ifndef __{0}", guardString).AppendLine()
                        .AppendFormat("#define __{0}", guardString).AppendLine()
                        .AppendLine()
                        .AppendLine()
                        .AppendFormat("#include \"{0}\"", options.ConfigHeaderFileName).AppendLine()
                        .AppendLine()
                        .AppendLine()
                        .AppendLine(header)
                        .AppendLine()
                        .AppendFormat("#endif // __{0}", guardString).AppendLine();

                    writer.Write(sb.ToString());
                }
            }
        }

        private void GenerateStateCode(UnitDeclaration unitDeclaration) {

            if (!String.IsNullOrEmpty(options.StateCodeFileName)) {
                using (StreamWriter writer = File.CreateText(options.StateCodeFileName)) {

                    string code = CodeGenerator.Generate(unitDeclaration);

                    StringBuilder sb = new StringBuilder();
                    sb
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine("// Generated by FsmCompiler v1.1")
                        .AppendLine("// Finite state machine compiler tool")
                        .AppendLine("// Copyright 2015-2020 Rafael Serrano (rsr.openware@gmail.com)")
                        .AppendLine("//")
                        .AppendLine("// Warning. Don't touch. Changes will be overwritten!")
                        .AppendLine("//")
                        .AppendLine("// -----------------------------------------------------------------------")
                        .AppendLine()
                        .AppendLine()
                        .AppendFormat("#include \"{0}\"", options.StateHeaderFileName).AppendLine()
                        .AppendFormat("#include \"{0}\"", options.ContextHeaderFileName).AppendLine()
                        .AppendLine()
                        .AppendLine()
                        .Append(code);

                    writer.Write(sb.ToString());
                }
            }
        }
    }
}
