#include "fsm_dump.h"

#include <stdlib.h>
#include <stdio.h>


struct VCD {
    FILE *file;
};


/// ----------------------------------------------------------------------
/// \brief Obra el fitxer de sortida.
/// \param fileName: Nom del fitxer.
/// \return El handler. NULL en cas d'error.
///
HVCD vcdOpen(const char *fileName) {
    
    HVCD hVcd = NULL;
    
    FILE *file = fopen(fileName, "wt");
    if (file) {
        hVcd = malloc(sizeof(struct VCD));
        if (hVcd) {
            hVcd->file = file;
            fprintf(file, "$date May 10 2017 00:00:00\n");
            fprintf(file, "$version Generated by 'fsm' $end\n");
            fprintf(file, "$timescale 1ns $end\n");
        }
    }
    
    return hVcd;
}


/// ----------------------------------------------------------------------
/// \brief Tanca el fitxer de sortida.
/// \param hVcd: El handler.
///
void vcdClose(HVCD hVcd) {
    
    if (hVcd) {
        if (hVcd->file)
            fclose(hVcd->file);
        free(hVcd);
    }
}


/// ----------------------------------------------------------------------
/// \brief Declara una senyal.
/// \param hVcd: El handler.
/// \param id: Identificador de la senyal.
/// \param name: Nom de la senyal per visualitzar.
///
void vcdDefineSignal(HVCD hVcd, const char *id, const char *name) {
    
    if (hVcd && hVcd->file)
        fprintf(hVcd->file, "$var wire 1 %s %s $end\n", id, name);
}


/// ----------------------------------------------------------------------
/// \brief Escriu la marca de temps.
/// \param hVcd: El handler.
/// \param time: La marca de temps.
///
void vcdWriteTime(HVCD hVcd, int time) {
    
    if (hVcd && hVcd->file)
        fprintf(hVcd->file, "#%d\n", time);
}


/// ----------------------------------------------------------------------
/// \brief Escriu la senyal.
/// \param hVcd: El handler.
/// \param id: Identificador de la senyal.
/// \param value: El valor de la senyal.
///
void vcdWriteSignal(HVCD hVcd, const char *id, int value) {
    
    if (hVcd && hVcd->file)
        fprintf(hVcd->file, "%d%s\n", value, id);
}